### ISSUE TITLE
Responsiveness of textarea

### ISSUE THREAD

**Issue by JoshuaPoddoku** [JoshuaPoddoku/TextBox#16]
https://github.com/JoshuaPoddoku/TextBox/tree/master/jquery

refer this one and I've integrated this into index.html for side number line bar.

**Comment by bikingbadger** [comment]
What exactly is required here. That the text box decrease or increase in size?

**Comment by precious-adeyinka** [comment]
I don't also get it? @JoshuaPoddoku Joshua... :thinking:

**Comment by precious-adeyinka** [comment]
I cant see the code for the number on the side of the textarea in the index.html file

**Comment by precious-adeyinka** [comment]
We might have to rethink that numbering line thing bro okay...
